# Generated by Django 3.1.5 on 2021-01-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20210125_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='city',
            field=models.CharField(choices=[('경기', '경기'), ('대전,충청', '대전,충청'), ('대구,경북', '대구,경북'), ('서울', '서울'), ('울산', '울산'), ('광주', '광주'), ('인천', '인천'), ('부산', '부산')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.CharField(choices=[('3~4(중수)', '3~4(중수)'), ('1~5(전체)', '1~5(전체)'), ('5(고수)', '5(고수)'), ('1~2(초보)', '1~2(초보)')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='sex',
            field=models.CharField(choices=[('남자만', '남자만'), ('남녀모두', '남녀모두'), ('여자만', '여자만')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(choices=[('17:00', '17:00'), ('09:00', '09:00'), ('11:00', '11:00'), ('13:00', '13:00'), ('15:00', '15:00'), ('21:00', '21:00'), ('19:00', '19:00')], max_length=80, null=True),
        ),
    ]
