# Generated by Django 3.1.5 on 2021-01-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='now_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.CharField(choices=[('seoul', '서울'), ('daejeon', '대전,충청'), ('ulsan', '울산'), ('incheon', '인천'), ('busan', '부산'), ('gwangju', '광주'), ('daegu', '대구,경북'), ('gyeonggi', '경기')], max_length=80, null=True),
        ),
    ]
