# Generated by Django 3.1.5 on 2021-01-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20210125_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='city',
            field=models.CharField(choices=[('부산', '부산'), ('광주', '광주'), ('서울', '서울'), ('대전,충청', '대전,충청'), ('대구,경북', '대구,경북'), ('인천', '인천'), ('울산', '울산'), ('경기', '경기')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='level',
            field=models.CharField(choices=[(3, '5(고수)'), (4, '1~5(전체)'), (1, '1~2(초보)'), (2, '3~4(중수)')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='sex',
            field=models.CharField(choices=[('여자만', '여자만'), ('남녀모두', '남녀모두'), ('남자만', '남자만')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(choices=[(13, '13:00'), (15, '15:00'), (21, '21:00'), (9, '09:00'), (11, '11:00'), (17, '17:00'), (19, '19:00')], max_length=80, null=True),
        ),
    ]
